Repository ervikasji/Hacktoberfest2K22, pull requests merged in 2022-10, with the labels that each got.

#2 added Only Folders
  DSA/maxTillI.cpp
  Web Developement/Backend Projects/welcome.html
  Web Developement/Frontend Projects/welcome.html
  Web Developement/Full-Stack Projects/welcome.html
  Web Developement/css/welcome.html
  Web Developement/html/welcome.html
  c++/maxTillI.cpp
  c/maxTillI.c
  python/maxTillI.py
Labels: good first issue, hacktoberfest-accepted

#3 uploaded portfolio website
  Web Developement/portfolio/.vscode/settings.json
  Web Developement/portfolio/img1.jpg
  Web Developement/portfolio/img2.jpg
  Web Developement/portfolio/index.html
  Web Developement/portfolio/style.css
Labels: good first issue, hacktoberfest-accepted

#4 Create flattering_of_list.py
  flattering_of_list.py
Labels: hacktoberfest-accepted

#6 Stack Evaluation
  c/StackEvaluation.c
Labels: hacktoberfest-accepted

#5 python docker tutorial
  python/python_docker_tutorial_1/Dockerfile
  python/python_docker_tutorial_1/hello_world.py
Labels: hacktoberfest-accepted

#9 Create StonePaperGame.py
  python/StonePaperGame.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#10 Create Calculator.c
  c/Calculator.c
Labels: hacktoberfest-accepted

#12 flood-fill
  c++/flood-fill.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#14 Create binarysearch.py
  binarysearch.py
Labels: hacktoberfest-accepted

#13 Create stooge_sort.py
  python/stooge_sort.py
Labels: hacktoberfest-accepted
